### ISSUE TITLE
find(): `start .. last` range doesn't seem functional

### ISSUE THREAD

**Issue by 747** [PMunch/strslice#1]
```nim
import strutils, strslice

var
  s = "0123456789"
  ss = s.toStringSlice

echo s.find("123", last = 5) # 1
echo s.find("456", last = 5) # -1
echo s.find("789", last = 5) # -1
echo ss.find("123", last = 5) # 1
echo ss.find("456", last = 5) # 4
echo ss.find("789", last = 5) # 7

echo ss.find("123", start = 2) # -1
echo ss.find("123", start = 2, last = 5) # Error: unhandled exception: index 10 not in 0 .. 9 [IndexError]
```

### Environment
```
👑 INim 0.4.1
Nim Compiler Version 0.20.0 [Linux: amd64]
```

**Comment by PMunch** [comment]
This should be fixed by: https://github.com/PMunch/strslice/commit/3cd7274d6294427db26dfbb67326d16aa1c05c64

But please verify, by the way you're running a pretty old version of Nim, might want to upgrade.

**Comment by 747** [comment]
Thank you. I'll check it out when I've got home.
For the version, yes, my environment has been long unmaintained, so I'll update too.

**Comment by 747** [comment]
Verified on my machine, with Nim 1.0.4.
